image: git.glade.ng:5050/engineering/docker-images/infra:latest

stages:
    - review
    - deploy-terraform
    - deploy-ansible
    - destroy

before_script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export ANSIBLE_INVENTORY=./ansible_inventory.ini
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY_PRIVATE" | tr -d ' ' | base64 --decode | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    

review:
    stage: review
    script:
        - cd terraform
        - terraform init
        - terraform fmt
        - terraform validate
        - terraform plan
    when: manual
      
deploy-terraform:
    stage: deploy-terraform
    script:
        - cd terraform
        - terraform init
        - terraform apply -auto-approve
    when: manual
    only:
        - production

deploy-ansible:
    stage: deploy-ansible
    script:
        - cd ansible
        - ansible-galaxy collection install ansible.posix
        - ansible all --list-hosts
        - ansible all -m ping --user ubuntu
        - ansible all -m setup --user ubuntu
        - ansible-playbook general-playbook.yml --extra-vars "gitlab_pat=$GITLAB_PAT"
    when: manual
    only:
        - production
    tags:
        - aws
