# Role link: https://galaxy.ansible.com/geerlingguy/apache
# Github Repo: https://github.com/geerlingguy/ansible-role-apache

apache_state: started
apache_enabled: yes
apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_port_ssl: 443
apache_create_vhosts: true
apache_remove_default_vhost: false
apache_global_vhost_settings: |
  DirectoryIndex index.php index.html
  SetEnv HTTP_GLADE_ENV production
  SetEnv HTTP_VERIF_HASH axXYN84lrqfRglG7o0203
  # Add other global settings on subsequent lines.
  <VirtualHost *:80>
    ServerName default
    #This part here, is crucial.
    <Location />
        Require all denied
    </Location>
  </VirtualHost>
  <VirtualHost *:443>
      ServerName default
      #This part here, is crucial.
      <Location />
          Require all denied
      </Location>
      SSLEngine on
      SSLCipherSuite AES256+EECDH:AES256+EDH
      SSLProtocol All -SSLv2 -SSLv3
      SSLHonorCipherOrder On
      SSLCompression off
      SSLCertificateFile /opt/glade/ssl/gladeng.crt-file
      SSLCertificateKeyFile /opt/glade/ssl/gladeng.key-file
      SSLCertificateChainFile /opt/glade/ssl/gladeng.bundle-file
  </VirtualHost>


apache_vhosts:
  # Additional optional properties: 'serveradmin, serveralias, extra_parameters'.
  - servername: '{{server_name}}'
    documentroot: '{{server_dir}}'
    extra_parameters: |
      ServerAlias *.glade.ng
      <Directory "/var/www/html/public">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        ReWriteEngine on
        ReWriteCond %{HTTP:X-Forwarded-Proto} !https
        ReWriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
      </Directory>

apache_vhosts_ssl:
  - servername: '{{server_name}}'
    documentroot: '{{server_dir}}'
    certificate_file: "/opt/glade/ssl/gladeng.crt-file"
    certificate_key_file: "/opt/glade/ssl/gladeng.key-file"
    certificate_chain_file: "/opt/glade/ssl/gladeng.bundle-file"
    extra_parameters: |
      ServerAlias *.glade.ng
      <Directory "/var/www/html/public">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        ReWriteEngine on
        RewriteCond %{HTTP_HOST} ^(.+\.)?glade.ng$ [NC]
        ReWriteRule ^(.*)$ https://%1gladefinance.co%{REQUEST_URI} [R=301,NC]
      </Directory>
  - servername: '{{server_name}}'
    documentroot: '{{server_dir}}'
    certificate_file: "/opt/glade/ssl/gladefinance.crt-file"
    certificate_key_file: "/opt/glade/ssl/gladefinance.key-file"
    certificate_chain_file: "/opt/glade/ssl/gladefinance.bundle-file"
    extra_parameters: |
      ServerAlias *.gladefinance.co
      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined
      

apache_allow_override: "All"
apache_options: "-Indexes +FollowSymLinks"
apache_ignore_missing_ssl_certificate: true
apache_mods_enabled:
  - rewrite
  - ssl
apache_mods_disabled: []
