# Role link: https://galaxy.ansible.com/geerlingguy/apache
# Github Repo: https://github.com/geerlingguy/ansible-role-apache

apache_state: started
apache_enabled: yes
apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_port_ssl: 443
apache_create_vhosts: true
apache_remove_default_vhost: false
apache_global_vhost_settings: |
  DirectoryIndex index.php index.html
  SetEnv HTTP_GLADE_ENV production
  SetEnv HTTP_VERIF_HASH axXYN84lrqfRglG7o0203
  # Add other global settings on subsequent lines.

apache_vhosts:
  # Additional optional properties: 'serveradmin, serveralias, extra_parameters'.
  - servername: '{{server_name}}'
    documentroot: '{{server_dir}}'
    extra_parameters: |
      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined

apache_vhosts_ssl:
  - servername: '{{server_name}}'
    documentroot: '{{server_dir}}'
    certificate_file: "/opt/glade/ssl/gladeng.crt-file"
    certificate_key_file: "/opt/glade/ssl/gladeng.key-file"
    certificate_chain_file: "/opt/glade/ssl/gladeng.bundle-file"
    extra_parameters: |
      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined

apache_allow_override: "All"
apache_options: "-Indexes +FollowSymLinks"
apache_ignore_missing_ssl_certificate: true
apache_mods_enabled:
  - rewrite
  - ssl
apache_mods_disabled: []
