# Role link: https://galaxy.ansible.com/geerlingguy/apache
# Github Repo: https://github.com/geerlingguy/ansible-role-apache

apache_state: started
apache_enabled: yes
apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_port_ssl: 443
apache_create_vhosts: true
apache_remove_default_vhost: false
apache_global_vhost_settings: |
  DirectoryIndex index.php index.html
  SetEnv HTTP_GLADE_ENV {{glade_env}}
  SetEnv HTTP_VERIF_HASH axXYN84lrqfRglG7o0203
  # Add other global settings on subsequent lines.

apache_vhosts:
  # Additional optional properties: 'serveradmin, serveralias, extra_parameters'.
  - servername: 'core-{{glade_env}}.glade.ng'
    documentroot: '/var/www/html/public'
    extra_parameters: |
      <Directory "/var/www/html/public">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        ReWriteEngine on
        ReWriteCond %{HTTP:X-Forwarded-Proto} !https
        ReWriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
      </Directory>
  - servername: 'db-{{glade_env}}.glade.ng'
    documentroot: '/var/www/html/public'
    extra_parameters: |
      <Directory "/var/www/html/public">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        ReWriteEngine on
        ReWriteCond %{HTTP:X-Forwarded-Proto} !https
        ReWriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
      </Directory>
  - servername: 'webhook-{{glade_env}}.glade.ng'
    documentroot: '/var/www/html/public'
    extra_parameters: |
      <Directory "/var/www/html/public">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        ReWriteEngine on
        ReWriteCond %{HTTP:X-Forwarded-Proto} !https
        ReWriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
      </Directory>
  - servername: 'checkout-{{glade_env}}.glade.ng'
    documentroot: '/var/www/html/public'
    extra_parameters: |
      <Directory "/var/www/html/public">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        ReWriteEngine on
        ReWriteCond %{HTTP:X-Forwarded-Proto} !https
        ReWriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
      </Directory>
  - servername: 'qc-{{glade_env}}.glade.ng'
    documentroot: '/var/www/html/public'
    extra_parameters: |
      <Directory "/var/www/html/public">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        ReWriteEngine on
        ReWriteCond %{HTTP:X-Forwarded-Proto} !https
        ReWriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
      </Directory>
  - servername: 'external-api-{{glade_env}}.glade.ng'
    documentroot: '/var/www/html/public'
    extra_parameters: |
      <Directory "/var/www/html/public">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        ReWriteEngine on
        ReWriteCond %{HTTP:X-Forwarded-Proto} !https
        ReWriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
      </Directory>
  - servername: 'mobile-api-{{glade_env}}.glade.ng'
    documentroot: '/var/www/html/public'
    extra_parameters: |
      <Directory "/var/www/html/public">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        ReWriteEngine on
        ReWriteCond %{HTTP:X-Forwarded-Proto} !https
        ReWriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
      </Directory>
  - servername: 'dashboard-{{glade_env}}.glade.ng'
    documentroot: '/var/www/web'
    extra_parameters: |
      <Directory "/var/www/web">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        ReWriteEngine on
        ReWriteCond %{HTTP:X-Forwarded-Proto} !https
        ReWriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
      </Directory>
  - servername: 'dashboard-api-{{glade_env}}.glade.ng'
    documentroot: '/var/www/html/public'
    extra_parameters: |
      <Directory "/var/www/html/public">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        ReWriteEngine on
        ReWriteCond %{HTTP:X-Forwarded-Proto} !https
        ReWriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
      </Directory>
  - servername: 'office-{{glade_env}}.glade.ng'
    documentroot: '/var/www/web'
    extra_parameters: |
      <Directory "/var/www/web">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        ReWriteEngine on
        ReWriteCond %{HTTP:X-Forwarded-Proto} !https
        ReWriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
      </Directory>
  - servername: 'office-api-{{glade_env}}.glade.ng'
    documentroot: '/var/www/html/public'
    extra_parameters: |
      <Directory "/var/www/html/public">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        ReWriteEngine on
        ReWriteCond %{HTTP:X-Forwarded-Proto} !https
        ReWriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
      </Directory>
  - servername: 'pay-{{glade_env}}.glade.ng'
    documentroot: '/var/www/web'
    extra_parameters: |
      <Directory "/var/www/web">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        ReWriteEngine on
        ReWriteCond %{HTTP:X-Forwarded-Proto} !https
        ReWriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
      </Directory>
    


apache_vhosts_ssl:
  - servername: 'core-{{glade_env}}.glade.ng'
    documentroot: '/var/www/core/public'
    certificate_file: "/opt/glade/ssl/gladeng.crt-file"
    certificate_key_file: "/opt/glade/ssl/gladeng.key-file"
    certificate_chain_file: "/opt/glade/ssl/gladeng.bundle-file"
    extra_parameters: |
      RewriteEngine on
  
  - servername: 'db-{{glade_env}}.glade.ng'
    documentroot: '/var/www/db/public'
    certificate_file: "/opt/glade/ssl/gladeng.crt-file"
    certificate_key_file: "/opt/glade/ssl/gladeng.key-file"
    certificate_chain_file: "/opt/glade/ssl/gladeng.bundle-file"
    extra_parameters: |
      RewriteEngine on
  
  - servername: 'webhook-{{glade_env}}.glade.ng'
    documentroot: '/var/www/webhook/public'
    certificate_file: "/opt/glade/ssl/gladeng.crt-file"
    certificate_key_file: "/opt/glade/ssl/gladeng.key-file"
    certificate_chain_file: "/opt/glade/ssl/gladeng.bundle-file"
    extra_parameters: |
      RewriteEngine on


  - servername: 'checkout-{{glade_env}}.glade.ng'
    documentroot: '/var/www/checkout/public'
    certificate_file: "/opt/glade/ssl/gladeng.crt-file"
    certificate_key_file: "/opt/glade/ssl/gladeng.key-file"
    certificate_chain_file: "/opt/glade/ssl/gladeng.bundle-file"
    extra_parameters: |
      RewriteEngine on


  - servername: 'qc-{{glade_env}}.glade.ng'
    documentroot: '/var/www/qc/public'
    certificate_file: "/opt/glade/ssl/gladeng.crt-file"
    certificate_key_file: "/opt/glade/ssl/gladeng.key-file"
    certificate_chain_file: "/opt/glade/ssl/gladeng.bundle-file"
    extra_parameters: |
      RewriteEngine on


  - servername: 'external-api-{{glade_env}}.glade.ng'
    documentroot: '/var/www/external-api/public'
    certificate_file: "/opt/glade/ssl/gladeng.crt-file"
    certificate_key_file: "/opt/glade/ssl/gladeng.key-file"
    certificate_chain_file: "/opt/glade/ssl/gladeng.bundle-file"
    extra_parameters: |
      RewriteEngine on

  
  - servername: 'mobile-api-{{glade_env}}.glade.ng'
    documentroot: '/var/www/mobile-api/public'
    certificate_file: "/opt/glade/ssl/gladeng.crt-file"
    certificate_key_file: "/opt/glade/ssl/gladeng.key-file"
    certificate_chain_file: "/opt/glade/ssl/gladeng.bundle-file"
    extra_parameters: |
      RewriteEngine on


  - servername: 'dashboard-{{glade_env}}.glade.ng'
    documentroot: '/var/www/dashboard'
    certificate_file: "/opt/glade/ssl/gladeng.crt-file"
    certificate_key_file: "/opt/glade/ssl/gladeng.key-file"
    certificate_chain_file: "/opt/glade/ssl/gladeng.bundle-file"
    extra_parameters: |
      RewriteEngine on
      SetEnv HTTP_GLADE_ENV {{glade_env}}
      SetEnv REACT_APP_DASHBOARD_BASE_URL https://dashboard-api-{{glade_env}}.glade.ng/api/v2
      SetEnv REACT_APP_CORE_BASE_URL https://core-{{glade_env}}.glade.ng
      SetEnv REACT_APP_APP_ENV development
      SetEnv REACT_APP_CHECKOUT_BASE_URL https://core-{{glade_env}}.glade.ng
      SetEnv REACT_APP_CHECKOUT_FILE_URL https://core-{{glade_env}}.glade.ng/checkout.js
      SetEnv REACT_APP_GLADE_PAYMENT_URL https://core-{{glade_env}}.glade.ng/checkout.js
      SetEnv REACT_APP_PAYMENT_PAGE_BASE_URL https://pay-{{glade_env}}.glade.ng
      SetEnv REACT_APP_APP_NAME Glade
      SetEnv REACT_APP_SLUG glade
      SetEnv REACT_APP_PUBLIC_URL
      SetEnv REACT_APP_API_URL https://dashboard-api-{{glade_env}}.glade.ng/api/v2/
      <Directory /var/www/dashboard/>
            Options FollowSymLinks
            AllowOverride All
            Require all granted

            AllowOverride All

            Options -MultiViews
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^ index.html [QSA,L]
      </Directory>

  - servername: 'dashboard-api-{{glade_env}}.glade.ng'
    documentroot: '/var/www/dashboard-api/public'
    certificate_file: "/opt/glade/ssl/gladeng.crt-file"
    certificate_key_file: "/opt/glade/ssl/gladeng.key-file"
    certificate_chain_file: "/opt/glade/ssl/gladeng.bundle-file"
    extra_parameters: |
      RewriteEngine on


  - servername: 'office-{{glade_env}}.glade.ng'
    documentroot: '/var/www/office'
    certificate_file: "/opt/glade/ssl/gladeng.crt-file"
    certificate_key_file: "/opt/glade/ssl/gladeng.key-file"
    certificate_chain_file: "/opt/glade/ssl/gladeng.bundle-file"
    extra_parameters: |
      RewriteEngine on
      <Directory /var/www/office>
            Options FollowSymLinks
            AllowOverride All
            Require all granted

            Options -MultiViews
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^ index.html [QSA,L]
        </Directory>

  - servername: 'office-api-{{glade_env}}.glade.ng'
    documentroot: '/var/www/office-api/public'
    certificate_file: "/opt/glade/ssl/gladeng.crt-file"
    certificate_key_file: "/opt/glade/ssl/gladeng.key-file"
    certificate_chain_file: "/opt/glade/ssl/gladeng.bundle-file"
    extra_parameters: |
      RewriteEngine on

  - servername: 'pay-{{glade_env}}.glade.ng'
    documentroot: '/var/www/pay'
    certificate_file: "/opt/glade/ssl/gladeng.crt-file"
    certificate_key_file: "/opt/glade/ssl/gladeng.key-file"
    certificate_chain_file: "/opt/glade/ssl/gladeng.bundle-file"
    extra_parameters: |
      RewriteEngine on
      RewriteCond %{HTTP:X-Forwarded-Proto} !https
      RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]
      <Directory "/var/www/pay">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        RewriteEngine on
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.html [QSA,L]
      </Directory>

apache_allow_override: "All"
apache_options: "-Indexes +FollowSymLinks"
apache_ignore_missing_ssl_certificate: true
apache_mods_enabled:
  - rewrite
  - ssl
apache_mods_disabled: []
