---
- name: Base Server Setup
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:
    - name: set timezone to Africa/Lagos
      timezone:
        name: Africa/Lagos
    - name: "Create required directories in for webserver"
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=x,o=x
      with_items:
      - /var/www/html/public
      - /opt/glade/logs
      - /opt/glade/keys
    - name: create default ssl directory
      file:
        path: /opt/glade/ssl
        state: directory
        mode: 0700
    - name: copy ssl files
      become: true 
      copy:
        src: ssl/
        dest: /opt/glade/ssl
        mode: 0600

- name: Setup Apache on sandbox Servers
  hosts: sandbox_servers
  remote_user: ubuntu
  become: true
  vars:
    glade_env: sandbox
  vars_files:
    - vars/apache-grouped.yml
  roles:
    - { role: geerlingguy.apache }

- name: Setup Apache on testing Servers
  hosts: testing_servers
  remote_user: ubuntu
  become: true
  vars:
    glade_env: testing
  vars_files:
    - vars/apache-grouped.yml
  roles:
    - { role: geerlingguy.apache }

- name: Setup Apache on canary Servers
  hosts: canary_servers
  remote_user: ubuntu
  become: true
  vars:
    glade_env: canary
  vars_files:
    - vars/apache-grouped.yml
  roles:
    - { role: geerlingguy.apache }

- name: Setup Apache on staging Servers
  hosts: staging_servers
  remote_user: ubuntu
  become: true
  vars:
    glade_env: staging
  vars_files:
    - vars/apache-grouped.yml
  roles:
    - { role: geerlingguy.apache }

- name: Setup Apache on experiment Servers
  hosts: experiment_servers
  remote_user: ubuntu
  become: true
  vars:
    glade_env: experiment
  vars_files:
    - vars/apache-grouped.yml
  roles:
    - { role: geerlingguy.apache }


- name: Setup Apache on Core Servers
  hosts: core
  remote_user: ubuntu
  become: true
  vars:
    server_name: core-external-prod-aws.glade.ng
    server_dir: /var/www/html/public
  vars_files:
    - vars/apache-prod.yml
  roles:
    - { role: geerlingguy.apache }

- name: Setup Apache on DB Servers
  hosts: db
  remote_user: ubuntu
  become: true
  vars:
    server_name: db-external-prod-aws.glade.ng
    server_dir: /var/www/html/public
  vars_files:
    - vars/apache-prod.yml
  roles:
    - { role: geerlingguy.apache }

- name: Setup Apache on dashboard Servers
  hosts: dashboard
  remote_user: ubuntu
  become: true
  vars:
    server_name: dashboard-external-prod-aws.glade.ng
    server_dir: /var/www/html/public
  vars_files:
    - vars/apache-prod.yml
  roles:
    - { role: geerlingguy.apache }

- name: Setup Apache on dashboard api Servers
  hosts: dashboard
  remote_user: ubuntu
  become: true
  vars:
    server_name: dashboard-api-external-prod-aws.glade.ng
    server_dir: /var/www/html/public
  vars_files:
    - vars/apache-prod.yml
  roles:
    - { role: geerlingguy.apache }

- name: Setup Apache on office Servers
  hosts: office
  remote_user: ubuntu
  become: true
  vars:
    server_name: office-external-prod-aws.glade.ng
    server_dir: /var/www/html/public
  vars_files:
    - vars/apache-prod.yml
  roles:
    - { role: geerlingguy.apache }

- name: Setup Apache on office api Servers
  hosts: office
  remote_user: ubuntu
  become: true
  vars:
    server_name: office-api-external-prod-aws.glade.ng
    server_dir: /var/www/html/public
  vars_files:
    - vars/apache-prod.yml
  roles:
    - { role: geerlingguy.apache }

- name: Setup Apache on qc Servers
  hosts: qc
  remote_user: ubuntu
  become: true
  vars:
    server_name: qc-external-prod-aws.glade.ng
    server_dir: /var/www/html/public
  vars_files:
    - vars/apache-prod.yml
  roles:
    - { role: geerlingguy.apache }

- name: Setup Apache on webhook Servers
  hosts: webhook
  remote_user: ubuntu
  become: true
  vars:
    server_name: webhoook-external-prod-aws.glade.ng
    server_dir: /var/www/html/public
  vars_files:
    - vars/apache-prod.yml
  roles:
    - { role: geerlingguy.apache }

- name: Setup Apache on mobile Servers
  hosts: mobile
  remote_user: ubuntu
  become: true
  vars:
    server_name: mobile-api-external-prod-aws.glade.ng
    server_dir: /var/www/html/public
  vars_files:
    - vars/apache-prod.yml
  roles:
    - { role: geerlingguy.apache }


- name: Setup Apache on external api Servers
  hosts: external
  remote_user: ubuntu
  become: true
  vars:
    server_name: external-api-external-prod-aws.glade.ng
    server_dir: /var/www/html/public
  vars_files:
    - vars/apache-prod.yml
  roles:
    - { role: geerlingguy.apache }

- name: Setup PHP Server
  hosts: all
  remote_user: ubuntu
  become: true
  vars_files:
    - vars/php-prod.yml
  vars:
    php_version: '8.1'
  roles:
    - geerlingguy.php-versions
    - geerlingguy.php

- name: grafana monitoring
  hosts: all
  remote_user: ubuntu
  become: true
  vars:
    loki_server: grafana.glade.ng
    glade_host_name: '{{  inventory_hostname  }}'
    promtail_version: 2.7.1
  tasks:
    - name: install acl package
      ansible.builtin.apt:
        name: acl
        state: present

    - name: create promtail group
      ansible.builtin.group:
        name: promtail
        state: present

    - name: create promtail user
      ansible.builtin.user:
        name: promtail
        groups:
          - promtail
          - systemd-journal
          - adm
        state: present
        system: true

    - name: set facl to allow promtail user to read /var/log contents
      ansible.posix.acl:
        path: /var/log
        entity: promtail
        etype: user
        permissions: rX
        state: present

    - name: make promtail user owner of /tmp/positions.yaml
      ansible.builtin.file:
        path: /tmp/positions.yaml
        owner: promtail
        group: promtail
        state: touch
        mode: 0750
      changed_when: false

    - name: install unzip package
      ansible.builtin.apt:
        name: unzip
        state: present

    - name: check if binary exists
      ansible.builtin.stat:
        path: /usr/bin/promtail-linux-amd64
      register: binary

    - name: check promtail version
      command: "sudo promtail-linux-amd64 --version"
      register: promtail_version_check
      when: binary.stat.exists
      changed_when: false

    - name: install promtail if its not present
      ansible.builtin.unarchive:
        src: "https://github.com/grafana/loki/releases/download/v\
            {{  promtail_version  }}/promtail-linux-amd64.zip"
        dest: /usr/bin/
        remote_src: true
      tags:
        - loki
      when: (not binary.stat.exists)

    - name: update promtail if different version is defined in variable
      ansible.builtin.unarchive:
        src: "https://github.com/grafana/loki/releases/download/v\
            {{  promtail_version  }}/promtail-linux-amd64.zip"
        dest: /usr/bin/
        remote_src: true
      tags:
        - loki
      when: (promtail_version_check | regex_search('\d.\d+.\d+') != promtail_version)
      notify: restart promtail

    - name: template systemd unit file
      ansible.builtin.template:
        src: templates/promtail.service.j2
        dest: /etc/systemd/system/promtail.service
        owner: root
        group: root
        mode: 0755
      tags:
        - loki

    - name: reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
      tags:
        - loki

    - name: make directory for promtail config
      ansible.builtin.file:
        path: /etc/promtail
        state: directory
        owner: root
        group: root
        mode: 0644

    - name: template promtail config file
      ansible.builtin.template:
        src: templates/promtail.yml.j2
        dest: /usr/local/bin/config-promtail.yml
        owner: root
        group: root
        mode: 0644

    - name: restart promtail
      become: true
      ansible.builtin.systemd:
        name: promtail
        enabled: true
        state: started
      changed_when: false

    - name: restart promtail
      ansible.builtin.systemd:
        name: promtail
        state: restarted
        enabled: true
